plugins {
    id 'net.fabricmc.fabric-loom'
}
//architectury {
//    common rootProject.enabled_platforms.split(',')
//}


dependencies {
    // We depend on Fabric Loader here to use the Fabric @Environment annotations,
    // which get remapped to the correct annotations on each platform.
    // Do NOT use other classes from Fabric Loader.
    minecraft "net.minecraft:minecraft:$rootProject.minecraft_version"

    implementation "net.fabricmc:fabric-loader:$rootProject.fabric_loader_version"


    implementation("maven.modrinth:iris:${project.iris_version}")
    implementation("com.github.zakgof:webp4j:0.0.2")
    implementation("org.scijava:native-lib-loader:2.3.2")
    implementation 'org.commonmark:commonmark:0.19.0'
    implementation 'org.jsoup:jsoup:1.15.4'
    implementation("com.github.weisj:jsvg:1.7.1")
    testImplementation 'org.junit.jupiter:junit-jupiter-api:5.8.2'
    testRuntimeOnly 'org.junit.jupiter:junit-jupiter-engine:5.8.2'
    testImplementation 'org.mockito:mockito-core:4.2.0'

}

base {
    archivesName = "$rootProject.archives_name-common"
}

repositories {
    maven { url = "https://maven.fabricmc.net/" }
}

configurations {
    transformProductionNeoForge {
        canBeResolved = false
        canBeConsumed = true
    }
}

artifacts {
    transformProductionNeoForge(jar)
}
